# Numpy
### Numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a collection of mathematical functions to operate on these arrays.
### Numpy is the fundamental package for scientific computing with Python.

In [4]:
import numpy as np
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
print(arr1.shape)

[1 2 3 4 5]
(5,)


In [5]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
arr2.shape

(2, 3)

In [6]:
arr3 = np.array([1, 2, 3, 4, 5, 6])
arr3.reshape(2, 3)  # Reshape to 2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
np.arange(0, 10, 2).reshape(5, 1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [10]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
## Identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Number of dimensions: ", arr.ndim)
print("Size (number of elements): ", arr.size)
print("Data type: ", arr.dtype)
print("Data type of elements: ", arr.dtype.name)
print("Item size (in bytes): ", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of dimensions:  2
Size (number of elements):  6
Data type:  int64
Data type of elements:  int64
Item size (in bytes):  8


In [13]:
# Numpy vectorized operations
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([6, 7, 8, 9, 10])

# Element-wise addition
print("Addition: ", arr1 + arr2)
# Element-wise subtraction
print("Subtraction: ", arr1 - arr2)
# Element-wise multiplication
print("Multiplication: ", arr1 * arr2)
# Element-wise division 
print("Division: ", arr1 / arr2)

Addition:  [ 7  9 11 13 15]
Subtraction:  [-5 -5 -5 -5 -5]
Multiplication:  [ 6 14 24 36 50]
Division:  [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [14]:
# Universal functions (ufuncs)
arr = np.array([1, 2, 3, 4, 5])
print("Square root: ", np.sqrt(arr)) # Square root of each element
print("Exponential: ", np.exp(arr)) # Exponential of each element
print("Logarithm: ", np.log(arr)) # Natural logarithm of each element
print("Sine: ", np.sin(arr)) # Sine of each element

Square root:  [1.         1.41421356 1.73205081 2.         2.23606798]
Exponential:  [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logarithm:  [0.         0.69314718 1.09861229 1.38629436 1.60943791]
Sine:  [ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [16]:
# Array slicing and indexing
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [8, 9, 10, 11]])
print("Original array: \n", arr)

Original array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 8  9 10 11]]


In [23]:
arr[0][0] # Accessing element at row 0, column 0
print(arr[0:2, 2:]) 

[[3 4]
 [7 8]]


In [20]:
arr[1:, 2:] # Accessing elements from row 1 to end and column 2 to end

array([[ 7,  8],
       [10, 11]])

In [24]:
# Modify array elements
arr[0] = [10, 11, 12, 13]
print("Modified array: \n", arr)
print("Row 1: ", arr[1]) # Accessing row 1
print("Column 2: ", arr[:, 2]) # Accessing column 2

Modified array: 
 [[10 11 12 13]
 [ 5  6  7  8]
 [ 8  9 10 11]]
Row 1:  [5 6 7 8]
Column 2:  [12  7 10]


In [25]:
# Practical example: Normalizing data
# Change data to have a mean of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

# Calculate mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data: ", normalized_data)

Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [26]:
# Calculation of mean, median, and standard deviation

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Array: \n", arr)
print("Mean: ", np.mean(arr)) # Mean of all elements
print("Mean along axis 0: ", np.mean(arr, axis=0)) # Mean along columns
print("Mean along axis 1: ", np.mean(arr, axis=1)) # Mean along rows
print("Median: ", np.median(arr)) # Median of all elements
print("Median along axis 0: ", np.median(arr, axis=0)) # Median along columns
print("Median along axis 1: ", np.median(arr, axis=1)) # Median along rows
print("Standard deviation: ", np.std(arr)) # Standard deviation of all elements
print("Standard deviation along axis 0: ", np.std(arr, axis=0)) # Standard deviation along columns
print("Standard deviation along axis 1: ", np.std(arr, axis=1)) # Standard deviation along rows

Array: 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Mean:  5.0
Mean along axis 0:  [4. 5. 6.]
Mean along axis 1:  [2. 5. 8.]
Median:  5.0
Median along axis 0:  [4. 5. 6.]
Median along axis 1:  [2. 5. 8.]
Standard deviation:  2.581988897471611
Standard deviation along axis 0:  [2.44948974 2.44948974 2.44948974]
Standard deviation along axis 1:  [0.81649658 0.81649658 0.81649658]


In [28]:
# Logical operations
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Data: ", data)
print("Elements greater than 5: ", data[data > 5]) # Elements greater than 5
print("Elements less than or equal to 5: ", data[data <= 5]) # Elements less than or equal to 5
print("Elements equal to 5: ", data[data == 5]) # Elements equal to 5
print("Elements not equal to 5: ", data[data != 5]) # Elements not equal to 5
print("Elements between 3 and 7: ", data[(data > 3) & (data < 7)]) # Elements between 3 and 7

Data:  [ 1  2  3  4  5  6  7  8  9 10]
Elements greater than 5:  [ 6  7  8  9 10]
Elements less than or equal to 5:  [1 2 3 4 5]
Elements equal to 5:  [5]
Elements not equal to 5:  [ 1  2  3  4  6  7  8  9 10]
Elements between 3 and 7:  [4 5 6]
